export default{
    name:'comment',
    title:'Comment',
    type:'document',
    fields:[
        {
            name:'name',
            type:'string'
        },
        {
            title:'Approuved',
            name:'approuved',
            type:'boolean',
            description:"Cannot see the comment without approuval"
        },
        {
            name:'email',
            type:'string',
        },
        {
            name:'comment',
            type:'text'
        },
        {
            name:'post',
            type:'reference',
            to:[{type:'post'}]
        }
    ]
}